name: Cloudflare Sync

on:
  repository_dispatch:
    types: [cf_update]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Fetch live.json from Cloudflare
        run: |
          set -eu
          mkdir -p data
          curl -fsSL "https://youtube-webhub.sochimaru-uo-wiki.workers.dev/live.json" -o data/live.json
          echo "Downloaded live.json size: $(wc -c < data/live.json) bytes"

      - name: Commit and push if changed
        run: |
          set -eu
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add data/live.json
          git diff --cached --quiet || (git commit -m "Update live.json from Cloudflare" && git push)
